# Veth class
# Configures and runs the veth program by Néstor Peña
# Only known website at time of writing is 
# http://www.geocities.ws/nestorjpg/veth/index.html

# SAVI McGill: Heming Wen, Prabhat Tiwary, Kevin Han, Michael Smith

import subprocess
class Veth:    

    def __init__(self):
        # Keep track of all created instances
        self.process_list = {}

    def start(self, attach_to, name, mac=0):
        """Starts an instance of vethd.  Returns PID.
        
        name = Name you want in the VIRTUAL device, for example: veth0
        attach_to = Name of the REAL device, for example: eth0, eth1
        mac = MAC address desired, like this: 00:11:22:33:44:55
        
        If mac is not specified, it is generated by the kernel."""
        if mac != 0 :
            command = ["vethd","-e", attach_to, "-v", name,"-m", mac]
        else:
            command = ["vethd","-e", attach_to,"-v", name]

        # Launch program
        process = subprocess.Popen(command)
        self.process_list[process.pid] = process
        
        return process.pid
        

    def stop(self, pid):
        """Stops the process with given PID, assuming it is a vethd process."""
        process = self.process_list.pop(pid)
        process.terminate()
        # Need .wait(), otherwise process hangs around as defunct.
        process.wait()

    def status(self, pid):
        """Returns the status of the given instance."""
        return self.process_list.get(pid).poll()
    
    def kill_all(self):
        """Kills all known vethd processes."""
        for key in self.process_list:
            process = self.process_list.pop(key)
            process.terminate()
            process.wait()
